version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8076:80"
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: project_nginx
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    command: >
      bash -c "composer install && php-fpm"
    volumes:
      - ./:/var/www/
        - /var/www/vendor
    container_name: project_app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1111
    ports:
      - "8101:5432"
    container_name: project_db
